services:
  couchbase:
    build: .
    ports:
      - "8091:8091"  # UI
      - "8092:8092"  # Views
      - "8093:8093"  # N1QL
      - "8094:8094"  # Full Text Search
      - "11210:11210"  # Data
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: admin
      COUCHBASE_ADMINISTRATOR_PASSWORD: password
      COUCHBASE_BUCKET: example_bucket
      COUCHBASE_BUCKET_REPLICAS: 1
    
